### ISSUE TITLE
Final commit

### ISSUE THREAD

**Issue by oselin** [oselin/diitpahomework1#12]

**Comment by oselin** [comment]
Buongiorno @DavidLeoni.

avrei bisogno di un paio di chiarimenti.

_all error signaling MUST be done C-style, with functions returning error codes in case of failures, which MUST be properly documented._

Significa che va sviluppata  una funzione `int errors(int expception)` oppure che bisogna utilizzare la libreria `signal.h`?

_each device MUST be dinamically allocated_

Significa che va creato un array con malloc() oppure è sufficiente come ho fatto?
~~~C++
cin >> ndevice;
for (int i=0; i<ndevice;i++){
structDevice = new structDevice;
//dosomething
~~~

Grazie

**Comment by DavidLeoni** [comment]
> Significa che va sviluppata una funzione int errors(int expception) oppure che bisogna utilizzare la libreria signal.h?

Per gli errori, teniamolo semplice: non serve usare funzioni o signal.h, basta che documenti nel testo delle tue funzioni cosa deve ritornare in caso di errore.

> Significa che va creato un array con malloc() oppure è sufficiente come ho fatto?

non ho ben capito:  creando i device dinamicamente, dovrai anche salvarti da qualche parte i puntatori alle struct. Non sapendo in anticipo il numero di device, dovrai per forza avere un array dinamico, a meno di non preallocare 100000 celle ma non mi sembra il caso.

Parlando d'altro, guardando il codice ho notato un paio di cose strane: 

- hai cancellato la directory tests in main,  spero che prima di consegnare ritorni :-)
- constrains se usato come nome va scritto constrain**t**s

**Comment by DavidLeoni** [comment]
> dovrai anche salvarti da qualche parte i puntatori alle struct.

Correggo:  invece di puntatori a struct,  puoi mettere direttamente le struct  tipo così:

```c++

struct MyDevice {
    int i;
};

int main() {

    MyDevice* arr;

    int n = 20;
    arr = new MyDevice[n];
    
    delete[] arr;
}
```

**Comment by DavidLeoni** [comment]
Mi devo ri-ricorreggere, propongo versione spero definitiva che salva i puntatori alle struct:

```c++
struct MyDevice {
    int i;
};

MyDevice* my_init_device(int i){
    cout << "Sto inizializzando " << i << endl;
    MyDevice* ret = new MyDevice;
    ret->i = i;
    return ret;
}

int main() {


    // SOLUZIONE CON ARRAY DINAMICO DI PUNTATORI A STRUCT
    
    MyDevice** arr;    // notare doppio asterisco

    int n = 2;
    arr = new MyDevice* [n];  // notare asterisco dopo MyDevice

    MyDevice* d1 = my_init_device(1);
    MyDevice* d2 = my_init_device(2);

    arr[0] = d1;
    arr[1] = d2;

    // ...

    // elimino un device alla volta
    delete arr[0];  // oppure my_destroy_device(arr[0])  se è definita
    delete arr[1];  // oppure my_destroy_device(arr[1])  se è definita
    // ....

    // poi elimino tutto l'array
    delete[] arr;
```

**Comment by oselin** [comment]
@DavidLeoni la ringrazio per tutti i suggerimenti. Per quanto riguarda la cartella tests provvedo a ricaricarla in serata.

Cordiali saluti

**Comment by oselin** [comment]
@DavidLeoni consegno l'homework.

Alcune note:
-Il loading/parsing della machine non è stato completato
-Il parsing del device funziona ma il codice non è snello e pulito, in quanto ho corretto in fretta i bug senza eliminare il "vecchio codice"
-Ho riadattato alcune funzioni del device preso in prestito in quanto le funzioni presenti andavano corrette. Non ho fatto in tempo a riadattare il mio codice alla libreria corretta

Buona serata
