### ISSUE TITLE
Loading from file

### ISSUE THREAD

**Issue by oselin** [oselin/diitpahomework1#3]
Feature 2: loading from file

**Comment by oselin** [comment]
Buongiorno @DavidLeoni,

nella loading feature è richiesto semplicemente di caricare il file .svg in una stringa oppure eseguire un parsing e riempire la struttura device con i dati importati?

**Comment by DavidLeoni** [comment]
Ho agigunto questo al doc del compito:

> - implement MyDevice* my_parse(string svg) function, which creates a struct from a SVG textual representation
> - implement load from file function

La load richiamerà la my_parse

**Comment by oselin** [comment]
@DavidLeoni la ringrazio. Buona giornata
