### ISSUE TITLE
SVG Approval

### ISSUE THREAD

**Issue by oselin** [oselin/diitpahomework1#5]
# SVG Approval

Buongiorno @DavidLeoni ,

io, @GiacomoCorradini e @riccardomenini abbiamo pensato di realizzare un camion trasportatore di auto. I tre disegni SVG saranno:
- Camion
- Rimorchio porta auto (già visibile nella repo)
- Auto

In questo modo riusciremmo a ottenere un disegno modulare, ognuno attingendo alle altre 2 repo. Tuttavia il disegno finale sarebbe lo stesso. 

Può andare bene ugualmente?

Sample:

![image](https://user-images.githubusercontent.com/57173644/114259821-200efd80-99d1-11eb-8e08-b921d87d4f10.png)

**Comment by DavidLeoni** [comment]
Buondì

i 3 svg di input e l'idea dell'autotrasportatore vanno bene, però vorrei che ognuno producesse una Machine diversa dagli altri. Magari un drone che consegna auto a domicilio?

Intanto segnate sul foglio condiviso i device di partenza che avete deciso, eventualmente per le Machine potete anche decidere in seguito facendo 'shopping' da altri repository.

@GiacomoCorradini  @riccardomenini

**Comment by oselin** [comment]
@DavidLeoni abbiamo pensato di realizzare Machine diverse creando combinazioni differenti dei singoli device (quindi usando solo il proprio svg + un secondo preso su github). In questo modo otterremmo 3 machine uniche.

Se questa può essere una buona soluzione, archivierei l'issue. 

Buona serata

**Comment by DavidLeoni** [comment]
ok!

@GiacomoCorradini @riccardomenini
